/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/concessionnaires/[idConcessionnaire]/': RouteRecordInfo<'/concessionnaires/[idConcessionnaire]/', '/concessionnaires/:idConcessionnaire', { idConcessionnaire: ParamValue<true> }, { idConcessionnaire: ParamValue<false> }>,
    '/concessionnaires/[idConcessionnaire]/modifier': RouteRecordInfo<'/concessionnaires/[idConcessionnaire]/modifier', '/concessionnaires/:idConcessionnaire/modifier', { idConcessionnaire: ParamValue<true> }, { idConcessionnaire: ParamValue<false> }>,
    '/concessionnaires/[idConcessionnaire]/voitures/creer': RouteRecordInfo<'/concessionnaires/[idConcessionnaire]/voitures/creer', '/concessionnaires/:idConcessionnaire/voitures/creer', { idConcessionnaire: ParamValue<true> }, { idConcessionnaire: ParamValue<false> }>,
    '/concessionnaires/creer': RouteRecordInfo<'/concessionnaires/creer', '/concessionnaires/creer', Record<never, never>, Record<never, never>>,
    '/voitures/[idVoiture]/modifier': RouteRecordInfo<'/voitures/[idVoiture]/modifier', '/voitures/:idVoiture/modifier', { idVoiture: ParamValue<true> }, { idVoiture: ParamValue<false> }>,
  }
}
